version: "3"
services:
  bot:
    build: .
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
